# List of Linux/security facts
facts_list = [
              'My name is Tux!',
              'Linux was created by Linus Torvalds',
              'Everything in Linux is a file',
              'The default user for su is the root user',
              'sudo commmand prompts users for their own password',
              'File permissions can be edited by the root user',
              'GRUB is a current Linux bootloader',
              'Linux bootloader loads the kernel',
              'Systemd uses targets',
              'inodes are data structures that contain file metadata',
              'Hard links are copies of the original file',
              'Soft links point to a filename',
              'mount lets you attach storage devices or filesystems',
              'chmod lets you add, remove, or change permissions',
              'A thread is an instance of execution',
              'top lets you view resource use',
              'renice lets you change a processes priority',
              ]